config/routes.rb
Rails.application.routes.draw do
  resources :file_msgs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_msg.rb
class FileMsg < ApplicationRecord
  mount_uploader :file_url, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/file_msgs_controller.rb
class FileMsgsController < ApplicationController
  before_action :set_file_msg, only: [:show, :edit, :update, :destroy]

  # GET /file_msgs
  # GET /file_msgs.json
  def index
    localfile = params[:localfile]
    s_file =  FileMsg.new
    Rails.logger.info "---1--#{localfile.inspect}"
    s_file.file_url = localfile
    s_file.save
    Rails.logger.info "---2--#{s_file.inspect}"

  end

  # GET /file_msgs/1
  # GET /file_msgs/1.json
  def show
  end

  # GET /file_msgs/new
  def new
    @file_msg = FileMsg.new
  end

  # GET /file_msgs/1/edit
  def edit
  end

  # POST /file_msgs
  # POST /file_msgs.json
  def create
    @file_msg = FileMsg.new(file_msg_params)

    respond_to do |format|
      if @file_msg.save
        format.html { redirect_to @file_msg, notice: 'File msg was successfully created.' }
        format.json { render :show, status: :created, location: @file_msg }
      else
        format.html { render :new }
        format.json { render json: @file_msg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_msgs/1
  # PATCH/PUT /file_msgs/1.json
  def update
    respond_to do |format|
      if @file_msg.update(file_msg_params)
        format.html { redirect_to @file_msg, notice: 'File msg was successfully updated.' }
        format.json { render :show, status: :ok, location: @file_msg }
      else
        format.html { render :edit }
        format.json { render json: @file_msg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_msgs/1
  # DELETE /file_msgs/1.json
  def destroy
    @file_msg.destroy
    respond_to do |format|
      format.html { redirect_to file_msgs_url, notice: 'File msg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_msg
      @file_msg = FileMsg.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def file_msg_params
      params.fetch(:file_msg, {})
    end
end

app/controllers/uploaders/avatar_uploader.rb
class AvatarUploader < CarrierWave::Uploader::Base
  # Include RMagick or MiniMagick support:
  # include CarrierWave::RMagick
  # include CarrierWave::MiniMagick

  # Choose what kind of storage to use for this uploader:
  storage :file
  # storage :fog

  # Override the directory where uploaded files will be stored.
  # This is a sensible default for uploaders that are meant to be mounted:
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  # Provide a default URL as a default if there hasn't been a file uploaded:
  # def default_url(*args)
  #   # For Rails 3.1+ asset pipeline compatibility:
  #   # ActionController::Base.helpers.asset_path("fallback/" + [version_name, "default.png"].compact.join('_'))
  #
  #   "/images/fallback/" + [version_name, "default.png"].compact.join('_')
  # end

  # Process files as they are uploaded:
  # process scale: [200, 300]
  #
  # def scale(width, height)
  #   # do something
  # end

  # Create different versions of your uploaded files:
  # version :thumb do
  #   process resize_to_fit: [50, 50]
  # end

  # Add a white list of extensions which are allowed to be uploaded.
  # For images you might use something like this:
  # def extension_whitelist
  #   %w(jpg jpeg gif png)
  # end

  # Override the filename of the uploaded files:
  # Avoid using model.id or version_name here, see uploader/store.rb for details.
  # def filename
  #   "something.jpg" if original_filename
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_msgs_helper.rb
module FileMsgsHelper
end

app/views/file_msgs/_form.html.erb
<%= form_with(model: file_msg, local: true) do |form| %>
  <% if file_msg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(file_msg.errors.count, "error") %> prohibited this file_msg from being saved:</h2>

      <ul>
      <% file_msg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/file_msgs/edit.html.erb
<h1>Editing File Msg</h1>

<%= render 'form', file_msg: @file_msg %>

<%= link_to 'Show', @file_msg %> |
<%= link_to 'Back', file_msgs_path %>

app/views/file_msgs/index.html.erb
<%= form_tag 'mystore', :multipart => true do%>
  <%= file_field_tag :localfile %>
  <%= submit_tag "上传"%>
<% end %>
<!--<p id="notice"><%#= notice %></p>-->

<!--<h1>File Msgs</h1>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
    <%# @file_msgs.each do |file_msg| %>
<!--      <tr>-->
<!--        <td><%#= link_to 'Show', file_msg %></td>-->
<!--        <td><%#= link_to 'Edit', edit_file_msg_path(file_msg) %></td>-->
<!--        <td><%#= link_to 'Destroy', file_msg, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<%#= link_to 'New File Msg', new_file_msg_path %>

app/views/file_msgs/new.html.erb
<h1>New File Msg</h1>

<%= render 'form', file_msg: @file_msg %>

<%= link_to 'Back', file_msgs_path %>

app/views/file_msgs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_file_msg_path(@file_msg) %> |
<%= link_to 'Back', file_msgs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carrierwave</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>